[book]
authors = ["Qiyao-Wang"]
language = "en"
multilingual = false
src = "src"
title = "Research-All-in-One"


[output.html]
site-url = "/research-all-in-on/"
default-theme = "light"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/QiYao-Wang/research-all-in-one"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
